### ISSUE TITLE
[Bug] clicking U after "removing an entire cell"

### ISSUE THREAD

**Issue by sofroniewn** [hci-unihd/covid-if-annotations#23]
@constantinpape first off this tool is amazing!! So awesome to see it come together so fast too.

I'm going through and trying out the dev version (installed from repo) and I encountered the following bug.

Load in unlabelled data, select `cell-segmentation` labels layer, use color picker to select label of a cell. Switch to fill bucket click on neighbouring cell to "merge" that cell with current one (i.e. in the event of over segmentation), click `u` to update layers, then make `infected-vs-control` points layer visible and I get the following index error

```python-traceback
Traceback (most recent call last):
  File "/Users/nsofroniew/GitHub/covid-if-annotations/napari_covid_if_annotations/gui.py", line 19, in <lambda>
    update_gui_btn.clicked.connect(lambda: update_layers(viewer))
  File "/Users/nsofroniew/GitHub/covid-if-annotations/napari_covid_if_annotations/_key_bindings.py", line 103, in update_layers
    viewer.layers['infected-vs-control'].refresh_colors()
  File "/Users/nsofroniew/GitHub/napari/napari/layers/points/points.py", line 991, in refresh_colors
    self._refresh_color('face', update_color_mapping)
  File "/Users/nsofroniew/GitHub/napari/napari/layers/points/points.py", line 1089, in _refresh_color
    color_event()
  File "/Users/nsofroniew/GitHub/napari/napari/utils/event.py", line 508, in __call__
    self._invoke_callback(cb, event)
  File "/Users/nsofroniew/GitHub/napari/napari/utils/event.py", line 529, in _invoke_callback
    cb_event=(cb, event),
  File "/Users/nsofroniew/GitHub/napari/napari/utils/event.py", line 523, in _invoke_callback
    cb(event)
  File "/Users/nsofroniew/GitHub/napari/napari/_vispy/vispy_points_layer.py", line 54, in _on_data_change
    edge_color = self.layer._view_edge_color
  File "/Users/nsofroniew/GitHub/napari/napari/layers/points/points.py", line 1334, in _view_edge_color
    return self.edge_color[self._indices_view]
IndexError: index 728 is out of bounds for axis 0 with size 728
```

Not sure if this is on napari end/ covid-if-annotator end, but wanted to document

**Comment by sofroniewn** [comment]
I'll note that "adding" a cell by drawing with a new color inside an old label works fine, as does just updating after editing an existing one

**Comment by constantinpape** [comment]
@sofroniewn  Thanks for reporting this bug, I can reproduce it:
- Deactivate `infected-vs-control`
- Select `cell-segmentation`
- Pick a segment colot, bucket fill another segment with it
- Press `u`

The line that throws in my code is the following:
```
  File "/home/pape/Work/covid/covid-if-annotations/napari_covid_if_annotations/_key_bindings.py", line 103, in update_layers
    viewer.layers['infected-vs-control'].refresh_colors()
```

This triggers then the following napari traceback:
```
  File "/home/pape/Work/software/conda/miniconda3/envs/test-annotations/lib/python3.8/site-packages/napari/layers/points/points.py", line 991, in refresh_colors
    self._refresh_color('face', update_color_mapping)
  File "/home/pape/Work/software/conda/miniconda3/envs/test-annotations/lib/python3.8/site-packages/napari/layers/points/points.py", line 1089, in _refresh_color
    color_event()
  File "/home/pape/Work/software/conda/miniconda3/envs/test-annotations/lib/python3.8/site-packages/napari/utils/event.py", line 508, in __call__
    self._invoke_callback(cb, event)
  File "/home/pape/Work/software/conda/miniconda3/envs/test-annotations/lib/python3.8/site-packages/napari/utils/event.py", line 525, in _invoke_callback
    _handle_exception(
  File "/home/pape/Work/software/conda/miniconda3/envs/test-annotations/lib/python3.8/site-packages/napari/utils/event.py", line 523, in _invoke_callback
    cb(event)
  File "/home/pape/Work/software/conda/miniconda3/envs/test-annotations/lib/python3.8/site-packages/napari/_vispy/vispy_points_layer.py", line 54, in _on_data_change
    edge_color = self.layer._view_edge_color
  File "/home/pape/Work/software/conda/miniconda3/envs/test-annotations/lib/python3.8/site-packages/napari/layers/points/points.py", line 1334, in _view_edge_color
    return self.edge_color[self._indices_view]
```

So I think the problem is that the state that is passed to `refresh_colors` is incosistent at this point.
Not that this issue does not occur if `infected-vs-control` is visible. 
So I think there might be a deeper napari issue underneath, but for now I think there is a simple fix on my side: only call `refresh_colors` if `infected-vs-control` is visible.
I will give it a try now.

**Comment by constantinpape** [comment]
Yes,
```python
if layer.visible:
  layer.refresh_colors()
```
fixed the issue.
Would still be interesting to now why the state is inconsistent if the layer is not visible.
