### ISSUE TITLE
Crashes on Linux

### ISSUE THREAD

**Issue by jkh1** [hci-unihd/covid-if-annotations#38]
Installing on Linux with conda:
```
> git clone https://github.com/hci-unihd/covid-if-annotations.git
> cd covid-if-annotations
> conda create -c conda-forge -n covid-if-annotations napari scikit-image h5py pandas
> conda activate covid-if-annotations
(covid-if-annotations) > pip install -e .
(covid-if-annotations) > covid_if_annotations
```
results in: 
```
Traceback (most recent call last):
  File "/home/heriche/miniconda3/envs/covid-if-annotations/bin/covid_if_annotations", line 33, in <module>
    sys.exit(load_entry_point('napari-covid-if-annotations', 'console_scripts', 'covid_if_annotations')())
  File "/home/heriche/Applications/covid-if-annotations/napari_covid_if_annotations/launcher/covid_if_annotations.py", line 150, in main
    launch_covid_if_annotation_tool(args.path, args.saturation_factor, args.edge_width)
  File "/home/heriche/Applications/covid-if-annotations/napari_covid_if_annotations/launcher/covid_if_annotations.py", line 134, in launch_covid_if_annotation_tool
    initialize_annotations(viewer, annotation_path)
  File "/home/heriche/Applications/covid-if-annotations/napari_covid_if_annotations/launcher/covid_if_annotations.py", line 23, in initialize_annotations
    with h5py.File(path, 'r') as f:
  File "/home/heriche/miniconda3/envs/covid-if-annotations/lib/python3.8/site-packages/h5py/_hl/files.py", line 395, in __init__
    name = filename_encode(name)
  File "/home/heriche/miniconda3/envs/covid-if-annotations/lib/python3.8/site-packages/h5py/_hl/compat.py", line 111, in filename_encode
    filename = fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not int
```
Providing a file with 
`(covid-if-annotations) > covid_if_annotations --path ~/Downloads/gt_image_001.h5`
produces the same error.

**Comment by constantinpape** [comment]
I forgot to update the command line interface to a recent change.
It's fixed now in 73db213f686e5
